---
core:
    num_workers: 100


inventory:
    plugin: nornir.plugins.inventory.simple.SimpleInventory
    options:
        host_file: "hosts.yml"
        group_file: "groups.yml"
        defaults_file: "defaults.yml"

runners:
    plugin: threaded
    options:
        num_workers: 10

logging:
    enabled: False