---
- name : PLAY configure interfaces and deploy OSPF
  hosts: multiarea
  connection: local
  gather_facts: no 
  tasks:
    - name: Create Loppback Interfaces
      with_items: "{{local_loopback}}"
      ios_interface:
        name: "{{item.name}}"
        enabled: True
        state: present
    - name: Set IPs address Loopbacks
      with_items: "{{local_loopback}}"
      ios_l3_interface:
        name: "{{item.name}}"
        ipv4: "{{item.ip_address}}"
    - name: Set IPs address Interfaces GigabitEthernet
      with_items: "{{interfaces}}"
      ios_l3_interface:
        name: "{{item.name}}"
        ipv4: "{{item.ip_address}}"
    - name: No shutdown GigabitEthernet Interfaces
      with_items: "{{interfaces}}"
      ios_interface:
        name: "{{item.name}}"
        enabled: True
        state: present
    - name: Generate configuration files cfg to all Devices
      template: src=files/ospf_jinja.j2 dest={{inventory_hostname}}.cfg
    
    - name: Deploy ospf configuration from file cfg
      ios_config:
        src: "{{inventory_hostname}}.cfg"