---
R1:
    hostname: 192.168.170.148
    platform: 'iosxe'
    username: devnet
    password: cisco
    groups:
        - cisco_group

R2:
    hostname: 192.168.170.149
    platform: 'iosxe'
    username: devnet
    password: cisco
    groups:
        - cisco_group

R3:
    hostname: 192.168.170.150
    platform: 'iosxe'
    username: devnet
    password: cisco
    groups:
        - cisco_group

R4:
    hostname: 192.168.170.151
    platform: 'iosxe'
    username: devnet
    password: cisco
    groups:
        - cisco_group