---
- name : configure Loopback interfaces from template
  hosts: multiarea
  connection: local
  gather_facts: no 
  
  tasks:
    - name: Create Loppback Interfaces
      include_vars:
        dir: host_vars
      with_items: "{{ loopback }}"
      template: src=files/ietf_interface.j2 dest="./output/{{ inventory_hostname }}/loopback.json"
    
   