---
- name : configure Loopback interfaces from template
  hosts: 10.10.20.100
  connection: local
  gather_facts: no 
  
  tasks:
    - name: Create Loppback Interfaces
      template: src=/files/ietf_interface.j2 dest="/output/{{ inventory_hostname }}/loopback.json"
      with_items: "{{loopback}}"
    
   