---
loopback:
  - name: Loopback0
    desc: "Loopback for router-id"
    ip_address: 2.2.2.2
    prefix: 255.255.255.255

interfaces:
  - name: GigabitEthernet2
    ip_address: 10.0.12.2/24
  - name: GigabitEthernet3
    ip_address: 10.2.24.2/24
  - name: GigabitEthernet4
    ip_address: 10.1.23.2/24

networks:
  - net: 2.2.2.2 
    mask: 0.0.0.0
    area_id: 0
  - net: 10.0.12.0 
    mask: 0.0.0.255
    area_id: 0
  - net: 10.1.23.0 
    mask: 0.0.0.255
    area_id: 1
  - net: 10.2.24.0 
    mask: 0.0.0.255
    area_id: 2

interface:
  - ospf_int: GigabitEthernet2
    area_id: 0
  - ospf_int: GigabitEthernet3
    area_id: 2
  - ospf_int: GigabitEthernet4
    area_id: 1

ospf_router_id: 2.2.2.2

ospf_process: 1
